feat: add flash mode in keyboard select patch
veltza/st-sx pull request #16
Opened 2024-12-27 02:51 UTC by DreamMaoMao

suppor move cursor in keyborad select like [flash.nvim](https://github.com/folke/flash.nvim)

https://github.com/user-attachments/assets/73f17628-bb04-45e7-9700-b0f1f58f0769

2024-12-27 09:45 UTC, veltza requested changes
Hey, this looks like a really cool feature! It will take me a while to review it because it's a fairly big PR, but that's okay.

In the meantime, you might want to check out these couple of things I quickly noticed.

2024-12-27 09:45 UTC, veltza commented on config.def.h
> +	{ ControlMask,          XK_i,           keyboard_flash,  { 0 } },
You can't use Ctrl+i as the default shortcut here because apps can use it too. For example, Vim uses that shortcut for its jump list. The default mask should be TERMMOD (Ctrl-Shift) and users can then change it as they like in their config.h file.

2024-12-27 09:45 UTC, veltza commented on st.h
> +	uint32_t mode;   /* attribute flags */
Can we still keep the mode field as ushort and move the ATTR_FLASH_LABEL to the extra field since bit 29 is free there? You could use the same name convention and change it to EXT_FLASH_LABEL.

2024-12-27 10:29 UTC, DreamMaoMao commented on st.h
> +	uint32_t mode;   /* attribute flags */
There is a serious exception with the 29th bit of extra, and I don't know why

2024-12-27 10:52 UTC, DreamMaoMao commented on st.h
> +	uint32_t mode;   /* attribute flags */
![image](https://github.com/user-attachments/assets/7b75a478-915a-4cab-aca7-22856900baf6)

I can confirm that there is nothing wrong with my logic, but once this position is used, it will cause the color rendering error of the next few characters, it seems that the 29 bit has other functions in the color rendering

2024-12-27 12:50 UTC, veltza commented on config.def.h
> +	{ ControlMask,          XK_i,           keyboard_flash,  { 0 } },
The keysym should be `XK_I` when the mask contains ShiftMask, otherwise it won't work.  This has fooled me a couple of times, because in the dwm configuration it does not have to be in capital letters in the corresponding case.

2024-12-27 13:36 UTC, DreamMaoMao commented on config.def.h
> +	{ ControlMask,          XK_i,           keyboard_flash,  { 0 } },
done

2024-12-27 21:10 UTC, veltza commented on patch/keyboardselect_st.c
> +        }
And the [xrealloc](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.c#L303-L310) function here.

2024-12-27 21:10 UTC, veltza commented on patch/keyboardselect_st.c
> +    }
```suggestion
	}
```

2024-12-27 21:10 UTC, veltza commented on patch/keyboardselect_st.c
> +    }
And the [xmalloc](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.c#L292-L301) function here too.

2024-12-27 21:10 UTC, veltza commented on patch/keyboardselect_st.c
> +        }
And the [xrealloc](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.c#L303-L310) function here too.

2024-12-28 00:44 UTC, DreamMaoMao commented on patch/keyboardselect_st.c
> +    }
done

2024-12-28 00:44 UTC, DreamMaoMao commented on patch/keyboardselect_st.c
> +    }
done

2024-12-28 00:44 UTC, DreamMaoMao commented on patch/keyboardselect_st.c
> +        }
done

2024-12-28 00:45 UTC, DreamMaoMao commented on patch/keyboardselect_st.c
> +        }
done

2024-12-28 13:35 UTC, veltza requested changes
I've thought this through and I've come to the conclusion that it's better to keep all attributes related to text rendering in the mode field because it makes the code more consistent.

So we increase the size of the mode field, but it requires more changes than changing the field type in the glyph structure. So here's the plan:

1. Add a new data type [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.h#L139) after the Rune type:
`typedef uint32_t Mode;`

2. Change the type of the mode field to `Mode` in the [glyph structure](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.h#L147).

3. Do the same [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/x.c#L72) in x.c on line 72.

4. And [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/x.c#L1496) in x.c on line 1496.

5. And [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/x.c#L1647) in x.c on line 1647 you can do this:
```c	
	Mode mode, prevmode = -1;
```

6. And finally [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/patch/openurlonclick.c#L257) in openurlonclick.c on line 257.

As you can see, changing the size of the mode field requires a lot of changes and that's why I was hesitant to do it, but now we do. The good thing is that since we've added this new data type, I can easily change the mode field back to the ushort type if one day I want to move the sixel attribute to the extra field for some reason.

Can you do this and then I think we're ready to merge this feature?

2024-12-28 13:48 UTC, DreamMaoMao commented
> I've thought this through and I've come to the conclusion that it's better to keep all attributes related to text rendering in the mode field because it makes the code more consistent.
> 
> So we increase the size of the mode field, but it requires more changes than changing the field type in the glyph structure. So here's the plan:
> 
> 1. Add a new data type [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.h#L138) after the Rune type:
>    `typedef uint32_t Mode;`
> 2. Change the type of the mode field to `Mode` in the [glyph structure](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/st.h#L147).
> 3. Do the same [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/x.c#L72) in x.c on line 72.
> 4. And [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/x.c#L1496) in x.c on line 1496.
> 5. And [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/x.c#L1647) in x.c on line 1647 you can do this:
> 
> ```c
> 	Mode mode, prevmode = -1;
> ```
> 
> 6. And finally [here](https://github.com/veltza/st-sx/blob/52cf6f0c912ba9f70e414864f23617313fb6e75a/patch/openurlonclick.c#L257) in openurlonclick.c on line 257.
> 
> As you can see, changing the size of the mode field requires a lot of changes and that's why I was hesitant to do it, but now we do. The good thing is that since we've added this new data type, I can easily change the mode field back to the ushort type if one day I want to move the sixel attribute to the extra field for some reason.
> 
> Can you do this and then I think we're ready to merge this feature?

done

2024-12-28 13:58 UTC, veltza commented
Damn you're fast, but too fast. Please check point 5 again. That's not right.

2024-12-28 14:16 UTC, DreamMaoMao commented
> Damn you're fast, but too fast. Please check point 5 again. That's not right.

done

2024-12-28 15:43 UTC, veltza approved these changes

2024-12-28 15:48 UTC, veltza commented
I will merge this tomorrow as I have some real life stuff to do. So if you still want to change something, feel free to do so.

2024-12-30 15:37 UTC, veltza requested changes
While I was fixing a few issues, I noticed a major design flaw in your code.

For example, in the kbds_ismatch function you take a 32-bit unicode character and pass it to insert_char_array() ...

```c
		insert_char_array(&flash_next_char_record, m.line[m.x].u);
```

... and here you truncate it to an 8-bit character.

```c
insert_char_array(CharArray *a, char element) {
    if (a->used == a->size) {
        a->size *= 2;
        a->array = (char *)xrealloc(a->array, a->size * sizeof(char));
    }
    a->array[a->used++] = element;
}
```

This can lead to all kinds of bugs. E.g. `š` can convert to `a` and so on.

Could you please check this out?

2024-12-30 22:35 UTC, veltza commented
I have gone through the code extensively and here is my attempt to change it to unicode compatible.  I didn't want to commit this yet because I want you to take a look at it first.

<details>
  <summary>Click me</summary>

```diff
diff --git a/patch/keyboardselect_st.c b/patch/keyboardselect_st.c
index 80302f7..d0bd447 100644
--- a/patch/keyboardselect_st.c
+++ b/patch/keyboardselect_st.c
@@ -34,7 +34,7 @@ struct {
 } kbds_searchobj;
 
 typedef struct {
-    char *array;
+    Rune *array;
     size_t used;
     size_t size;
 } CharArray;
@@ -65,16 +65,16 @@ static const char *flash_key_label[52] = {
 
 void
 init_char_array(CharArray *a, size_t initialSize) {
-    a->array = (char *)xmalloc(initialSize * sizeof(char));
+    a->array = (Rune *)xmalloc(initialSize * sizeof(Rune));
     a->used = 0;
     a->size = initialSize;
 }
 
 void
-insert_char_array(CharArray *a, char element) {
+insert_char_array(CharArray *a, Rune element) {
     if (a->used == a->size) {
         a->size *= 2;
-        a->array = (char *)xrealloc(a->array, a->size * sizeof(char));
+        a->array = (Rune *)xrealloc(a->array, a->size * sizeof(Rune));
     }
     a->array[a->used++] = element;
 }
@@ -113,109 +113,9 @@ reset_kcursor_array(KCursorArray *a) {
     a->size = 0;
 }
 
-char
-keysym_to_char(unsigned int keysym) {
-    switch (keysym) {
-        case XK_0: return '0';
-        case XK_1: return '1';
-        case XK_2: return '2';
-        case XK_3: return '3';
-        case XK_4: return '4';
-        case XK_5: return '5';
-        case XK_6: return '6';
-        case XK_7: return '7';
-        case XK_8: return '8';
-        case XK_9: return '9';
-        case XK_KP_0: return '0';
-        case XK_KP_1: return '1';
-        case XK_KP_2: return '2';
-        case XK_KP_3: return '3';
-        case XK_KP_4: return '4';
-        case XK_KP_5: return '5';
-        case XK_KP_6: return '6';
-        case XK_KP_7: return '7';
-        case XK_KP_8: return '8';
-        case XK_KP_9: return '9';
-        case XK_exclam: return '!';
-        case XK_at: return '@';
-        case XK_numbersign: return '#';
-        case XK_dollar: return '$';
-        case XK_percent: return '%';
-        case XK_asciicircum: return '^';
-        case XK_ampersand: return '&';
-        case XK_asterisk: return '*';
-        case XK_parenleft: return '(';
-        case XK_parenright: return ')';
-        case XK_minus: return '-';
-        case XK_underscore: return '_';
-        case XK_equal: return '=';
-        case XK_plus: return '+';
-		case XK_period : return '.';
-        case XK_BackSpace: return '\b';
-        case XK_Tab: return '\t';
-        case XK_Linefeed: return '\n';
-        case XK_Return: return '\r';
-        case XK_space: return ' ';
-        case XK_a: return 'a';
-        case XK_b: return 'b';
-        case XK_c: return 'c';
-        case XK_d: return 'd';
-        case XK_e: return 'e';
-        case XK_f: return 'f';
-        case XK_g: return 'g';
-        case XK_h: return 'h';
-        case XK_i: return 'i';
-        case XK_j: return 'j';
-        case XK_k: return 'k';
-        case XK_l: return 'l';
-        case XK_m: return 'm';
-        case XK_n: return 'n';
-        case XK_o: return 'o';
-        case XK_p: return 'p';
-        case XK_q: return 'q';
-        case XK_r: return 'r';
-        case XK_s: return 's';
-        case XK_t: return 't';
-        case XK_u: return 'u';
-        case XK_v: return 'v';
-        case XK_w: return 'w';
-        case XK_x: return 'x';
-        case XK_y: return 'y';
-        case XK_z: return 'z';
-        case XK_A: return 'A';
-        case XK_B: return 'B';
-        case XK_C: return 'C';
-        case XK_D: return 'D';
-        case XK_E: return 'E';
-        case XK_F: return 'F';
-        case XK_G: return 'G';
-        case XK_H: return 'H';
-        case XK_I: return 'I';
-        case XK_J: return 'J';
-        case XK_K: return 'K';
-        case XK_L: return 'L';
-        case XK_M: return 'M';
-        case XK_N: return 'N';
-        case XK_O: return 'O';
-        case XK_P: return 'P';
-        case XK_Q: return 'Q';
-        case XK_R: return 'R';
-        case XK_S: return 'S';
-        case XK_T: return 'T';
-        case XK_U: return 'U';
-        case XK_V: return 'V';
-        case XK_W: return 'W';
-        case XK_X: return 'X';
-        case XK_Y: return 'Y';
-        case XK_Z: return 'Z';
-        default: return '?'; // Unknown keysym
-    }
-}
-
 int
-is_in_flash_used_label(unsigned int keysym) {
+is_in_flash_used_label(Rune label) {
 	int i;
-	char label = keysym_to_char(keysym);
 	for ( i = 0; i < flash_used_label.used; i++) {
 		if (label == flash_used_label.array[i]) {
 			return 1;
@@ -225,9 +125,8 @@ is_in_flash_used_label(unsigned int keysym) {
 }
 
 int
-is_in_flash_next_char_record(unsigned int keysym) {
+is_in_flash_next_char_record(Rune label) {
 	int i;
-	char label = keysym_to_char(keysym);
 	for ( i = 0; i < flash_next_char_record.used; i++) {
 		if (label == flash_next_char_record.array[i]) {
 			return 1;
@@ -590,6 +489,7 @@ kbds_ismatch(KCursor c)
 {
 	KCursor m = c;
 	int i, next;
+	Rune u;
 
 	if (c.x + kbds_searchobj.len > c.len && (!kbds_iswrapped(&c) || c.y >= kbds_bot()))
 		return 0;
@@ -618,7 +518,8 @@ kbds_ismatch(KCursor c)
 
 	if (kbds_isflashmode()) {
 		m.line[m.x].ubk = m.line[m.x].u;
-		insert_char_array(&flash_next_char_record, m.line[m.x].u);
+		u = kbds_searchobj.ignorecase ? towlower(m.line[m.x].u) : m.line[m.x].u;
+		insert_char_array(&flash_next_char_record, u);
 		insert_kcursor_array(&flash_kcursor_record, m);
 	}
 
@@ -680,9 +581,8 @@ kbds_searchall(void)
 }
 
 void
-jump_to_label(unsigned int keysym, int len) {
+jump_to_label(Rune label, int len) {
 	int i;
-	char label = keysym_to_char(keysym);
 	for ( i = 0; i < flash_kcursor_record.used; i++) {
 		if (label == flash_kcursor_record.array[i].line[flash_kcursor_record.array[i].x].u) {
 			kbds_moveto(flash_kcursor_record.array[i].x-len, flash_kcursor_record.array[i].y);
@@ -911,21 +811,21 @@ kbds_keyboardhandler(KeySym ksym, char *buf, int len, int forcequit)
 			return 0;
 		default:
 			if (len > 0) {
-				if (is_in_flash_used_label(ksym) == 1) {
-					jump_to_label(ksym,kbds_searchobj.len);
+				utf8decode(buf, &u, len);
+				if (is_in_flash_used_label(u) == 1) {
+					jump_to_label(u, kbds_searchobj.len);
 					kbds_searchobj.len = 0;
 					kbds_setmode(kbds_mode & ~KBDS_MODE_FLASH);
 					clear_flash_cache();
 					kbds_clearhighlights();
 					kbds_selecttext();
 					return 0;
-				} else if(ksym,kbds_searchobj.len > 0 && is_in_flash_next_char_record(ksym) == 0) {
+				} else if (kbds_searchobj.len > 0 && is_in_flash_next_char_record(u) == 0) {
 					return 0;
 				} else {
 					clear_flash_cache();
 				}
 				kbds_clearhighlights();
-				utf8decode(buf, &u, len);
 				kbds_insertchar(u);
 				for (kbds_searchobj.ignorecase = 1, i = 0; i < kbds_searchobj.len; i++) {
 					if (kbds_searchobj.str[i].u != towlower(kbds_searchobj.str[i].u)) {
```

</details>

2024-12-31 02:30 UTC, DreamMaoMao commented
> I have gone through the code extensively and here is my attempt to change it to unicode compatible. I didn't want to commit this yet because I want you to take a look at it first.
> 
> Click me

I think it makes sense that these changes are necessary

2024-12-31 12:59 UTC, veltza commented
I'm very close to merging this, but one last question before that.

Could you please explain this code to me? In particular, what is the purpose of the inner if statement?

```c
	if (!(base.mode & (ATTR_HIGHLIGHT | ATTR_REVERSE | ATTR_WDUMMY | ATTR_FLASH_LABEL)) && kbds_isflashmode()) {
		fg = &dc.col[flashtextfg];
		if (base.bg != defaultbg)
			bg = &dc.col[flashtextbg];
	}
```

2024-12-31 13:24 UTC, DreamMaoMao commented
> I'm very close to merging this, but one last question before that.
> 
> Could you please explain this code to me? In particular, what is the purpose of the inner if statement?
> 
> ```c
> 	if (!(base.mode & (ATTR_HIGHLIGHT | ATTR_REVERSE | ATTR_WDUMMY | ATTR_FLASH_LABEL)) && kbds_isflashmode()) {
> 		fg = &dc.col[flashtextfg];
> 		if (base.bg != defaultbg)
> 			bg = &dc.col[flashtextbg];
> 	}
> ```


![image](https://github.com/user-attachments/assets/604bc0ed-c527-49d0-a486-89c4b31e4569)
![image](https://github.com/user-attachments/assets/cbefa16f-52b0-4570-99de-d7557eb1b5af)

The purpose is to
1. make the transparent background remain transparent(defaultbg),
2. non-transparent background is forced to be converted to the set flashtextbg, because only under flashtextbg, flashtextfg has a strong highlight. If flashtextbg is not set, text with a background color will not be visible once it has the same color as flashtextfg

2024-12-31 15:16 UTC, veltza approved these changes

2024-12-31 15:20 UTC, merged