feat: Support auto scroll when use mouse to select
veltza/st-sx pull request #9
Opened 2024-08-28 10:43 UTC by leihaojun

2024-08-28 18:36 UTC, veltza commented on x.c
> +} ScroolDirection;
Should be `ScrollDirection`

2024-08-28 18:36 UTC, veltza commented on x.c
> +	ScroolDirection dir;
Should be `ScrollDirection`

2024-08-28 18:38 UTC, veltza commented on x.c
> +			asr->isscrolling = 1;
There is redundancy code here. It is difficult and error-prone to maintain code if the same code is repeated.

2024-08-28 18:42 UTC, veltza commented on x.c
> +		timeout = asr->iscontinue ? timeout : -1;
Do you know what value is stored in the **timeout** variable before this statement, because I don't?
It could be **minlatency**, **blinktimeout**, **cursorblinktimeout** or **something in between**.

So if there is blinking text on the screen, what do you think will happen to the scrolling speed?

2024-08-29 00:26 UTC, leihaojun commented on x.c
> +} ScroolDirection;
fixed

2024-08-29 00:26 UTC, leihaojun commented on x.c
> +	ScroolDirection dir;
fixed

2024-08-29 00:26 UTC, leihaojun commented on x.c
> +			asr->isscrolling = 1;
fixed

2024-08-29 00:27 UTC, leihaojun commented on x.c
> +		timeout = asr->iscontinue ? timeout : -1;
The judgment here did not take into account the mouse's delayed effects, which have since been fixed

2024-08-29 10:47 UTC, veltza requested changes

2024-08-29 10:47 UTC, veltza commented on x.c
> +	if ((e->xbutton.y < borderpx || e->xbutton.y > win.h - borderpx) && asr.isbutton1press) {
The text area doesn't necessarily end at `win.h - borderpx`.
The correct way to calculate the bottom of the text area is:
`int bot = term.row * win.ch + borderpx - 1;`

It means that the text area is in the inclusive range [borderpx, bot].

2024-08-29 10:47 UTC, veltza commented on x.c
> +		}
Is `isscrolling` variable really needed? Can it be removed from the entire implementation?

2024-08-29 10:47 UTC, veltza commented on x.c
> +	int target_scrolltimeout = 0;
```suggestion
	double target_scrolltimeout;
```

2024-08-29 10:47 UTC, veltza commented on x.c
> +
```suggestion
		/*
		 * The distance between the mouse and the window is x.
		 * The next scroll time is reduced by y.
		 * y = x^2 - 2*x.
		 * target_scrolltimeout is the final timeout value which minimum value is 1.
		*/
		if (asr.iscontinue == 1) {
			target_scrolltimeout = disable_autoscroll_accelerate
				? autoscrolltimeout
				: MAX((double)autoscrolltimeout - (asr.speed) * (asr.speed) - (asr.speed) * 2, 1.0);
			if (target_scrolltimeout - TIMEDIFF(now, lastscroll) <= 0) {
				if (asr.dir == SCROLL_UP)
					kscrollup(&(Arg){.i = 1});
				else
					kscrolldown(&(Arg){.i = 1});
				xyselextend(asr.buttonx, asr.buttony, asr.seltype);
				lastscroll = now;
			}
			timeout = target_scrolltimeout - TIMEDIFF(now, lastscroll);
			asr.isscrolling = 1;
		}
		else {
			asr.isscrolling = 0;
		}

```

Notes.
* I simplified the outer if statement because the asr.dir variable only has two states.
* I changed the autoscrolltimeout variable to double.
* Timeouts are calculated inside the if statement.
* We can override the timeout variable because screen scrolling is the most important timer.

2024-08-29 12:22 UTC, leihaojun commented on x.c
> +		}
you can't remove it,otherwise, the mouse will not be able to end automatic scrolling when it is released outside the window.

2024-08-29 12:29 UTC, leihaojun commented on x.c
> +
`timeout = target_scrolltimeout - TIMEDIFF(now, lastscroll);`
The judgment here is not perfect, we must ensure that timeout is `> 0`, otherwise on the next loop, it will be blocked in the above `pselect` and cannot scroll again.

2024-08-29 16:56 UTC, veltza commented on x.c
> +	if ((e->xbutton.y < borderpx || e->xbutton.y > win.h - borderpx) && asr.isbutton1press) {
Could you fix this as well? It's important.

The if statement should be:
`	if ((e->xbutton.y < borderpx || e->xbutton.y > bot) && asr.isbutton1press) {
`

And the speed calculation should be:
`		asr.speed = e->xbutton.y < borderpx ? abs(e->xbutton.y - borderpx) : e->xbutton.y - bot;
`

2024-08-29 17:03 UTC, veltza commented on config.def.h
> + */
This is just a suggestion. Would it be more descriptive this way?

```suggestion
/*
 * Specifies how fast the screen scrolls when you select text and drag the
 * mouse to the top or bottom of the screen.
 */
```

2024-08-29 17:24 UTC, veltza commented on config.def.h
> +
Again, this is just a suggestion. I prefer that variables that are related to each other are named the same way. So this could be:

```suggestion
/*
 * When enabled, the speed of autoscroll is affected by the distance between
 * the mouse pointer and the window.
 */
static unsigned int autoscrollacceleration = 1;
```

But if you change it like this, then also note that its meaning changes to the opposite and that must be taken into account in the code.

But if you prefer the current variable name, then leave it be.

2024-08-29 23:20 UTC, leihaojun commented on config.def.h
> +
fix

2024-08-29 23:20 UTC, leihaojun commented on config.def.h
> + */
fix

2024-08-30 08:48 UTC, veltza commented
We're almost done, but could you do a couple more things?

1. Add the `autoscrolltimeout` and `autoscrollacceleration` variables to the [resources](https://github.com/veltza/st-sx/blob/1f3e76c648d5dc6711270641850302cd50a12fd7/config.def.h#L622) table so they can also be set via Xresources.
2. Also add them to the [xresources-example](https://github.com/veltza/st-sx/blob/main/xresources-example) file after the St.ligatures variable.

2024-08-30 09:52 UTC, leihaojun commented
> We're almost done, but could you do a couple more things?
> 
> 1. Add the `autoscrolltimeout` and `autoscrollacceleration` variables to the [resources](https://github.com/veltza/st-sx/blob/1f3e76c648d5dc6711270641850302cd50a12fd7/config.def.h#L622) table so they can also be set via Xresources.
> 2. Also add them to the [xresources-example](https://github.com/veltza/st-sx/blob/main/xresources-example) file after the St.ligatures variable.

done

2024-08-30 10:18 UTC, veltza commented
I was wondering if the acceleration could just be a multiplier? Then users could also adjust the acceleration to their liking.

Suggestion:

config.def.h

```c
/* Specifies how fast the autoscroll accelerates. Set to 0 to disable
 * acceleration. */
static float autoscrollacceleration = 1.0;
```

x.c
```c
target_scrolltimeout = MAX((double)autoscrolltimeout -
	autoscrollacceleration * (asr.speed * asr.speed + asr.speed * 2), 1.0);
```

What do you think?

2024-08-30 10:26 UTC, leihaojun commented
This calculation is the practice of most terminals at present, and the advantage of this is that you can switch between slow and extremely fast speeds in very short moving distances. Because the distance between the upper and lower screen boundaries after the terminal is covered with the screen is very short.

2024-08-30 10:56 UTC, veltza commented
I think I messed up the math. That's how it should be, right?

```c
target_scrolltimeout = MAX((double)autoscrolltimeout -
	autoscrollacceleration * (asr.speed * asr.speed - asr.speed * 2), 1.0);
```

2024-08-30 11:04 UTC, leihaojun commented
Yeah, I just fixed it

2024-08-30 11:07 UTC, leihaojun commented
![image](https://github.com/user-attachments/assets/f064adf1-ab4a-45a1-9335-d3cef5ddb1d6)

In order to keep y from being negative when the distance is 1, we need to add one to correct for the deviation

2024-08-30 11:55 UTC, veltza requested changes

2024-08-30 11:55 UTC, veltza commented on config.def.h
> + * the larger the value, the greater the change in scroll speed.
This sentence does not make any sense.

2024-08-30 11:55 UTC, veltza commented on .vscode/settings.json
> +}
Why do you want to add this file?

2024-08-30 12:22 UTC, leihaojun commented on .vscode/settings.json
> +}
Accident, deleted

2024-08-30 12:23 UTC, leihaojun commented on config.def.h
> + * the larger the value, the greater the change in scroll speed.
Feel free to modify it

2024-08-30 12:43 UTC, veltza commented on config.def.h
> + * the larger the value, the greater the change in scroll speed.
I had a [suggestion up there](https://github.com/veltza/st-sx/pull/9#issuecomment-2320762934) and I think it is sufficient.
Users will understand it, or if they don't, they will figure it out.

2024-08-30 14:59 UTC, veltza approved these changes

2024-08-30 20:05 UTC, merged

2024-08-30 20:08 UTC, veltza commented
Thanks for the contribution!